services:
  loki:
    image: grafana/loki:2.9.0
    volumes:
      - ./loki/config/loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./promtail/config/config.yaml:/etc/promtail/config.yml